name: build

on:
  push:
    tags:
      - 'v*'

permissions:
  id-token: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: checkout_repo
      uses: actions/checkout@v3
    - name: install_buildx
      uses: docker/setup-buildx-action@v2
    - name: build_release
      run: |
        TARGET_VERSION="$(echo ${{ github.ref_name }} | cut -c 2-)"
        export ACTIONS_CACHE_URL=$(echo "$ACTIONS_ID_TOKEN_REQUEST_URL" | grep -Po 'https://[^/]+/[^/]+/' | sed  's/pipelines/artifactcache/')
        export ACTIONS_RUNTIME_TOKEN=$ACTIONS_ID_TOKEN_REQUEST_TOKEN

        docker buildx build --build-arg TARGET_VERSION="$TARGET_VERSION" --cache-to "type=gha,mode=max,scope=build" --cache-from "type=gha,scope=build" . \
          --target=output --output type=local,dest=/tmp/out/
        cp /tmp/out/VmChamp /tmp/out/VmChamp-linux-${{ github.ref_name }}-amd64
    - name: upload_binary
      uses: actions/upload-artifact@v3.1.2
      with:
        name: "VmChamp-linux-${{ github.ref_name }}-amd64"
        path: /tmp/out/VmChamp
        retention-days: 1
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        body: |
          ${{ github.event.head_commit.message }}
        files: /tmp/out/VmChamp-linux-${{ github.ref_name }}-amd64
